### ISSUE TITLE
添加 description 以优化 GitHub 站内搜索 SEO

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/Open-Source-Fans-Manifesto#3]

**Comment by zhuangbiaowei** [comment]
description ，加在什么位置呢？

**Comment by stevending1st** [comment]
> description ，加在什么位置呢？

![image](https://user-images.githubusercontent.com/23376142/160581984-28c12d17-7239-4cdf-b6ae-87f4d9df29b1.png)
![image](https://user-images.githubusercontent.com/23376142/160582484-1b420781-811d-4a3b-a3a5-688474bb206f.png)

**Comment by zhuangbiaowei** [comment]
加好了
